apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: test-argo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: app.fundevops.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-tutorial-goapp
                port:
                  number: 80
  tls:
    - hosts:
        - app.fundevops.store
      secretName: app-tls
