apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-tutorial
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Himanshu-216/argocd-tutorial.git
    targetRevision: master
    path: charts

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: test-argo   # ðŸ‘ˆ deploy here

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   # ðŸ‘ˆ auto-create namespace
